# Generated by Django 3.1.4 on 2022-04-22 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='professionalskills',
            old_name='skillDetail',
            new_name='skill_detail',
        ),
    ]
