# Generated by Django 3.1.4 on 2022-04-22 08:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0002_auto_20220422_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='degree',
            field=models.CharField(choices=[('Phd', 'Phd'), ('Mtech/MA/MSc/MCom/MBA', 'Mtech/MA/MSc/MCom/MBA'), ('BE/Btech/BA/BSc/BCom', 'BE/Btech/BA/BSc/BCom'), ('12th', '12th')], max_length=50),
        ),
    ]
