# Generated by Django 3.1.4 on 2022-04-22 10:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0008_auto_20220422_1521'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='passing_year',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='projectorjob',
            name='end_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 15, 51, 1, 119077)),
        ),
        migrations.AlterField(
            model_name='projectorjob',
            name='start_date',
            field=models.DateField(default=datetime.datetime(2022, 4, 22, 15, 51, 1, 119077)),
        ),
    ]
