# Generated by Django 3.1.4 on 2022-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0010_auto_20220422_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='mobile',
            field=models.IntegerField(default=0, max_length=10),
            preserve_default=False,
        ),
    ]
