# Generated by Django 3.1.4 on 2022-04-22 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0011_person_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='mobile',
            field=models.IntegerField(),
        ),
    ]
