# Generated by Django 3.1.4 on 2022-04-22 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0013_auto_20220423_0021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='education',
            name='description',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='person',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6),
        ),
    ]
