# Generated by Django 3.1.4 on 2022-04-22 19:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0015_auto_20220423_0033'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='education',
            name='passing_year',
        ),
        migrations.RemoveField(
            model_name='education',
            name='result',
        ),
    ]
